// Code generated by gowrap. DO NOT EDIT.
// template: schema.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package hcloud

import (
	"github.com/hetznercloud/hcloud-go/v2/hcloud/schema"
)

//go:generate go run github.com/hexdigest/gowrap/cmd/gowrap gen -g -p . -i converter -t schema.tmpl -o schema.go

// This file provides converter functions to convert models in the
// schema package to models in the hcloud package and vice versa.

var c converter

// ActionFromSchema converts schema.Action to *Action.
func ActionFromSchema(a1 schema.Action) (ap1 *Action) {
	return c.ActionFromSchema(a1)
}

// ActionsFromSchema converts []schema.Action to []*Action.
func ActionsFromSchema(aa1 []schema.Action) (apa1 []*Action) {
	return c.ActionsFromSchema(aa1)
}

// CertificateFromSchema converts schema.Certificate to *Certificate.
func CertificateFromSchema(c1 schema.Certificate) (cp1 *Certificate) {
	return c.CertificateFromSchema(c1)
}

// DatacenterFromSchema converts schema.Datacenter to *Datacenter.
func DatacenterFromSchema(d1 schema.Datacenter) (dp1 *Datacenter) {
	return c.DatacenterFromSchema(d1)
}

// DeprecationFromSchema converts *schema.DeprecationInfo to *DeprecationInfo.
func DeprecationFromSchema(dp1 *schema.DeprecationInfo) (dp2 *DeprecationInfo) {
	return c.DeprecationFromSchema(dp1)
}

// ErrorFromSchema converts schema.Error to Error.
func ErrorFromSchema(e1 schema.Error) (e2 Error) {
	return c.ErrorFromSchema(e1)
}

// FirewallFromSchema converts schema.Firewall to *Firewall.
func FirewallFromSchema(f1 schema.Firewall) (fp1 *Firewall) {
	return c.FirewallFromSchema(f1)
}

// FloatingIPFromSchema converts schema.FloatingIP to *FloatingIP.
func FloatingIPFromSchema(f1 schema.FloatingIP) (fp1 *FloatingIP) {
	return c.FloatingIPFromSchema(f1)
}

// ISOFromSchema converts schema.ISO to *ISO.
func ISOFromSchema(i1 schema.ISO) (ip1 *ISO) {
	return c.ISOFromSchema(i1)
}

// ImageFromSchema converts schema.Image to *Image.
func ImageFromSchema(i1 schema.Image) (ip1 *Image) {
	return c.ImageFromSchema(i1)
}

// LoadBalancerFromSchema converts schema.LoadBalancer to *LoadBalancer.
func LoadBalancerFromSchema(l1 schema.LoadBalancer) (lp1 *LoadBalancer) {
	return c.LoadBalancerFromSchema(l1)
}

// LoadBalancerMetricsFromSchema converts *schema.LoadBalancerGetMetricsResponse to *LoadBalancerMetrics.
func LoadBalancerMetricsFromSchema(lp1 *schema.LoadBalancerGetMetricsResponse) (lp2 *LoadBalancerMetrics, err error) {
	return c.LoadBalancerMetricsFromSchema(lp1)
}

// LoadBalancerServiceFromSchema converts schema.LoadBalancerService to LoadBalancerService.
func LoadBalancerServiceFromSchema(l1 schema.LoadBalancerService) (l2 LoadBalancerService) {
	return c.LoadBalancerServiceFromSchema(l1)
}

// LoadBalancerServiceHealthCheckFromSchema converts *schema.LoadBalancerServiceHealthCheck to LoadBalancerServiceHealthCheck.
func LoadBalancerServiceHealthCheckFromSchema(lp1 *schema.LoadBalancerServiceHealthCheck) (l1 LoadBalancerServiceHealthCheck) {
	return c.LoadBalancerServiceHealthCheckFromSchema(lp1)
}

// LoadBalancerTargetFromSchema converts schema.LoadBalancerTarget to LoadBalancerTarget.
func LoadBalancerTargetFromSchema(l1 schema.LoadBalancerTarget) (l2 LoadBalancerTarget) {
	return c.LoadBalancerTargetFromSchema(l1)
}

// LoadBalancerTargetHealthStatusFromSchema converts schema.LoadBalancerTargetHealthStatus to LoadBalancerTargetHealthStatus.
func LoadBalancerTargetHealthStatusFromSchema(l1 schema.LoadBalancerTargetHealthStatus) (l2 LoadBalancerTargetHealthStatus) {
	return c.LoadBalancerTargetHealthStatusFromSchema(l1)
}

// LoadBalancerTargetServerFromSchema converts schema.LoadBalancerTargetServer to LoadBalancerTargetServer.
func LoadBalancerTargetServerFromSchema(l1 schema.LoadBalancerTargetServer) (l2 LoadBalancerTargetServer) {
	return c.LoadBalancerTargetServerFromSchema(l1)
}

// LoadBalancerTypeFromSchema converts schema.LoadBalancerType to *LoadBalancerType.
func LoadBalancerTypeFromSchema(l1 schema.LoadBalancerType) (lp1 *LoadBalancerType) {
	return c.LoadBalancerTypeFromSchema(l1)
}

// LoadBalancerTypeLocationPricingFromSchema converts schema.PricingLoadBalancerTypePrice to LoadBalancerTypeLocationPricing.
func LoadBalancerTypeLocationPricingFromSchema(p1 schema.PricingLoadBalancerTypePrice) (l1 LoadBalancerTypeLocationPricing) {
	return c.LoadBalancerTypeLocationPricingFromSchema(p1)
}

// LocationFromSchema converts schema.Location to *Location.
func LocationFromSchema(l1 schema.Location) (lp1 *Location) {
	return c.LocationFromSchema(l1)
}

// NetworkFromSchema converts schema.Network to *Network.
func NetworkFromSchema(n1 schema.Network) (np1 *Network) {
	return c.NetworkFromSchema(n1)
}

// NetworkRouteFromSchema converts schema.NetworkRoute to NetworkRoute.
func NetworkRouteFromSchema(n1 schema.NetworkRoute) (n2 NetworkRoute) {
	return c.NetworkRouteFromSchema(n1)
}

// NetworkSubnetFromSchema converts schema.NetworkSubnet to NetworkSubnet.
func NetworkSubnetFromSchema(n1 schema.NetworkSubnet) (n2 NetworkSubnet) {
	return c.NetworkSubnetFromSchema(n1)
}

// PaginationFromSchema converts schema.MetaPagination to Pagination.
func PaginationFromSchema(m1 schema.MetaPagination) (p1 Pagination) {
	return c.PaginationFromSchema(m1)
}

// PlacementGroupFromSchema converts schema.PlacementGroup to *PlacementGroup.
func PlacementGroupFromSchema(p1 schema.PlacementGroup) (pp1 *PlacementGroup) {
	return c.PlacementGroupFromSchema(p1)
}

// PriceFromSchema converts schema.Price to Price.
func PriceFromSchema(p1 schema.Price) (p2 Price) {
	return c.PriceFromSchema(p1)
}

// PricingFromSchema converts schema.Pricing to Pricing.
func PricingFromSchema(p1 schema.Pricing) (p2 Pricing) {
	return c.PricingFromSchema(p1)
}

// PrimaryIPFromSchema converts schema.PrimaryIP to *PrimaryIP.
func PrimaryIPFromSchema(p1 schema.PrimaryIP) (pp1 *PrimaryIP) {
	return c.PrimaryIPFromSchema(p1)
}

// SSHKeyFromSchema converts schema.SSHKey to *SSHKey.
func SSHKeyFromSchema(s1 schema.SSHKey) (sp1 *SSHKey) {
	return c.SSHKeyFromSchema(s1)
}

// SchemaFromAction converts *Action to schema.Action.
func SchemaFromAction(ap1 *Action) (a1 schema.Action) {
	return c.SchemaFromAction(ap1)
}

// SchemaFromActions converts []*Action to []schema.Action.
func SchemaFromActions(apa1 []*Action) (aa1 []schema.Action) {
	return c.SchemaFromActions(apa1)
}

// SchemaFromCertificate converts *Certificate to schema.Certificate.
func SchemaFromCertificate(cp1 *Certificate) (c1 schema.Certificate) {
	return c.SchemaFromCertificate(cp1)
}

// SchemaFromDatacenter converts *Datacenter to schema.Datacenter.
func SchemaFromDatacenter(dp1 *Datacenter) (d1 schema.Datacenter) {
	return c.SchemaFromDatacenter(dp1)
}

// SchemaFromDeprecation converts *DeprecationInfo to *schema.DeprecationInfo.
func SchemaFromDeprecation(dp1 *DeprecationInfo) (dp2 *schema.DeprecationInfo) {
	return c.SchemaFromDeprecation(dp1)
}

// SchemaFromError converts Error to schema.Error.
func SchemaFromError(e1 Error) (e2 schema.Error) {
	return c.SchemaFromError(e1)
}

// SchemaFromFirewall converts *Firewall to schema.Firewall.
func SchemaFromFirewall(fp1 *Firewall) (f1 schema.Firewall) {
	return c.SchemaFromFirewall(fp1)
}

// SchemaFromFirewallCreateOpts converts FirewallCreateOpts to schema.FirewallCreateRequest.
func SchemaFromFirewallCreateOpts(f1 FirewallCreateOpts) (f2 schema.FirewallCreateRequest) {
	return c.SchemaFromFirewallCreateOpts(f1)
}

// SchemaFromFirewallResource converts FirewallResource to schema.FirewallResource.
func SchemaFromFirewallResource(f1 FirewallResource) (f2 schema.FirewallResource) {
	return c.SchemaFromFirewallResource(f1)
}

// SchemaFromFirewallSetRulesOpts converts FirewallSetRulesOpts to schema.FirewallActionSetRulesRequest.
func SchemaFromFirewallSetRulesOpts(f1 FirewallSetRulesOpts) (f2 schema.FirewallActionSetRulesRequest) {
	return c.SchemaFromFirewallSetRulesOpts(f1)
}

// SchemaFromFloatingIP converts *FloatingIP to schema.FloatingIP.
func SchemaFromFloatingIP(fp1 *FloatingIP) (f1 schema.FloatingIP) {
	return c.SchemaFromFloatingIP(fp1)
}

// SchemaFromISO converts *ISO to schema.ISO.
func SchemaFromISO(ip1 *ISO) (i1 schema.ISO) {
	return c.SchemaFromISO(ip1)
}

// SchemaFromImage converts *Image to schema.Image.
func SchemaFromImage(ip1 *Image) (i1 schema.Image) {
	return c.SchemaFromImage(ip1)
}

// SchemaFromLoadBalancer converts *LoadBalancer to schema.LoadBalancer.
func SchemaFromLoadBalancer(lp1 *LoadBalancer) (l1 schema.LoadBalancer) {
	return c.SchemaFromLoadBalancer(lp1)
}

// SchemaFromLoadBalancerAddServiceOpts converts LoadBalancerAddServiceOpts to schema.LoadBalancerActionAddServiceRequest.
func SchemaFromLoadBalancerAddServiceOpts(l1 LoadBalancerAddServiceOpts) (l2 schema.LoadBalancerActionAddServiceRequest) {
	return c.SchemaFromLoadBalancerAddServiceOpts(l1)
}

// SchemaFromLoadBalancerCreateOpts converts LoadBalancerCreateOpts to schema.LoadBalancerCreateRequest.
func SchemaFromLoadBalancerCreateOpts(l1 LoadBalancerCreateOpts) (l2 schema.LoadBalancerCreateRequest) {
	return c.SchemaFromLoadBalancerCreateOpts(l1)
}

// SchemaFromLoadBalancerCreateOptsTargetServer converts LoadBalancerCreateOptsTargetServer to schema.LoadBalancerCreateRequestTargetServer.
func SchemaFromLoadBalancerCreateOptsTargetServer(l1 LoadBalancerCreateOptsTargetServer) (l2 schema.LoadBalancerCreateRequestTargetServer) {
	return c.SchemaFromLoadBalancerCreateOptsTargetServer(l1)
}

// SchemaFromLoadBalancerServerTarget converts LoadBalancerTargetServer to schema.LoadBalancerTargetServer.
func SchemaFromLoadBalancerServerTarget(l1 LoadBalancerTargetServer) (l2 schema.LoadBalancerTargetServer) {
	return c.SchemaFromLoadBalancerServerTarget(l1)
}

// SchemaFromLoadBalancerService converts LoadBalancerService to schema.LoadBalancerService.
func SchemaFromLoadBalancerService(l1 LoadBalancerService) (l2 schema.LoadBalancerService) {
	return c.SchemaFromLoadBalancerService(l1)
}

// SchemaFromLoadBalancerServiceHealthCheck converts LoadBalancerServiceHealthCheck to *schema.LoadBalancerServiceHealthCheck.
func SchemaFromLoadBalancerServiceHealthCheck(l1 LoadBalancerServiceHealthCheck) (lp1 *schema.LoadBalancerServiceHealthCheck) {
	return c.SchemaFromLoadBalancerServiceHealthCheck(l1)
}

// SchemaFromLoadBalancerTarget converts LoadBalancerTarget to schema.LoadBalancerTarget.
func SchemaFromLoadBalancerTarget(l1 LoadBalancerTarget) (l2 schema.LoadBalancerTarget) {
	return c.SchemaFromLoadBalancerTarget(l1)
}

// SchemaFromLoadBalancerTargetHealthStatus converts LoadBalancerTargetHealthStatus to schema.LoadBalancerTargetHealthStatus.
func SchemaFromLoadBalancerTargetHealthStatus(l1 LoadBalancerTargetHealthStatus) (l2 schema.LoadBalancerTargetHealthStatus) {
	return c.SchemaFromLoadBalancerTargetHealthStatus(l1)
}

// SchemaFromLoadBalancerType converts *LoadBalancerType to schema.LoadBalancerType.
func SchemaFromLoadBalancerType(lp1 *LoadBalancerType) (l1 schema.LoadBalancerType) {
	return c.SchemaFromLoadBalancerType(lp1)
}

// SchemaFromLoadBalancerTypeLocationPricing converts LoadBalancerTypeLocationPricing to schema.PricingLoadBalancerTypePrice.
func SchemaFromLoadBalancerTypeLocationPricing(l1 LoadBalancerTypeLocationPricing) (p1 schema.PricingLoadBalancerTypePrice) {
	return c.SchemaFromLoadBalancerTypeLocationPricing(l1)
}

// SchemaFromLoadBalancerUpdateServiceOpts converts LoadBalancerUpdateServiceOpts to schema.LoadBalancerActionUpdateServiceRequest.
func SchemaFromLoadBalancerUpdateServiceOpts(l1 LoadBalancerUpdateServiceOpts) (l2 schema.LoadBalancerActionUpdateServiceRequest) {
	return c.SchemaFromLoadBalancerUpdateServiceOpts(l1)
}

// SchemaFromLocation converts *Location to schema.Location.
func SchemaFromLocation(lp1 *Location) (l1 schema.Location) {
	return c.SchemaFromLocation(lp1)
}

// SchemaFromNetwork converts *Network to schema.Network.
func SchemaFromNetwork(np1 *Network) (n1 schema.Network) {
	return c.SchemaFromNetwork(np1)
}

// SchemaFromNetworkRoute converts NetworkRoute to schema.NetworkRoute.
func SchemaFromNetworkRoute(n1 NetworkRoute) (n2 schema.NetworkRoute) {
	return c.SchemaFromNetworkRoute(n1)
}

// SchemaFromNetworkSubnet converts NetworkSubnet to schema.NetworkSubnet.
func SchemaFromNetworkSubnet(n1 NetworkSubnet) (n2 schema.NetworkSubnet) {
	return c.SchemaFromNetworkSubnet(n1)
}

// SchemaFromPagination converts Pagination to schema.MetaPagination.
func SchemaFromPagination(p1 Pagination) (m1 schema.MetaPagination) {
	return c.SchemaFromPagination(p1)
}

// SchemaFromPlacementGroup converts *PlacementGroup to schema.PlacementGroup.
func SchemaFromPlacementGroup(pp1 *PlacementGroup) (p1 schema.PlacementGroup) {
	return c.SchemaFromPlacementGroup(pp1)
}

// SchemaFromPlacementGroupCreateOpts converts PlacementGroupCreateOpts to schema.PlacementGroupCreateRequest.
func SchemaFromPlacementGroupCreateOpts(p1 PlacementGroupCreateOpts) (p2 schema.PlacementGroupCreateRequest) {
	return c.SchemaFromPlacementGroupCreateOpts(p1)
}

// SchemaFromPricing converts Pricing to schema.Pricing.
func SchemaFromPricing(p1 Pricing) (p2 schema.Pricing) {
	return c.SchemaFromPricing(p1)
}

// SchemaFromPrimaryIP converts *PrimaryIP to schema.PrimaryIP.
func SchemaFromPrimaryIP(pp1 *PrimaryIP) (p1 schema.PrimaryIP) {
	return c.SchemaFromPrimaryIP(pp1)
}

// SchemaFromPrimaryIPAssignOpts converts PrimaryIPAssignOpts to schema.PrimaryIPActionAssignRequest.
func SchemaFromPrimaryIPAssignOpts(p1 PrimaryIPAssignOpts) (p2 schema.PrimaryIPActionAssignRequest) {
	return c.SchemaFromPrimaryIPAssignOpts(p1)
}

// SchemaFromPrimaryIPChangeDNSPtrOpts converts PrimaryIPChangeDNSPtrOpts to schema.PrimaryIPActionChangeDNSPtrRequest.
func SchemaFromPrimaryIPChangeDNSPtrOpts(p1 PrimaryIPChangeDNSPtrOpts) (p2 schema.PrimaryIPActionChangeDNSPtrRequest) {
	return c.SchemaFromPrimaryIPChangeDNSPtrOpts(p1)
}

// SchemaFromPrimaryIPChangeProtectionOpts converts PrimaryIPChangeProtectionOpts to schema.PrimaryIPActionChangeProtectionRequest.
func SchemaFromPrimaryIPChangeProtectionOpts(p1 PrimaryIPChangeProtectionOpts) (p2 schema.PrimaryIPActionChangeProtectionRequest) {
	return c.SchemaFromPrimaryIPChangeProtectionOpts(p1)
}

// SchemaFromPrimaryIPCreateOpts converts PrimaryIPCreateOpts to schema.PrimaryIPCreateRequest.
func SchemaFromPrimaryIPCreateOpts(p1 PrimaryIPCreateOpts) (p2 schema.PrimaryIPCreateRequest) {
	return c.SchemaFromPrimaryIPCreateOpts(p1)
}

// SchemaFromPrimaryIPUpdateOpts converts PrimaryIPUpdateOpts to schema.PrimaryIPUpdateRequest.
func SchemaFromPrimaryIPUpdateOpts(p1 PrimaryIPUpdateOpts) (p2 schema.PrimaryIPUpdateRequest) {
	return c.SchemaFromPrimaryIPUpdateOpts(p1)
}

// SchemaFromSSHKey converts *SSHKey to schema.SSHKey.
func SchemaFromSSHKey(sp1 *SSHKey) (s1 schema.SSHKey) {
	return c.SchemaFromSSHKey(sp1)
}

// SchemaFromServer converts *Server to schema.Server.
func SchemaFromServer(sp1 *Server) (s1 schema.Server) {
	return c.SchemaFromServer(sp1)
}

// SchemaFromServerPrivateNet converts ServerPrivateNet to schema.ServerPrivateNet.
func SchemaFromServerPrivateNet(s1 ServerPrivateNet) (s2 schema.ServerPrivateNet) {
	return c.SchemaFromServerPrivateNet(s1)
}

// SchemaFromServerPublicNet converts ServerPublicNet to schema.ServerPublicNet.
func SchemaFromServerPublicNet(s1 ServerPublicNet) (s2 schema.ServerPublicNet) {
	return c.SchemaFromServerPublicNet(s1)
}

// SchemaFromServerPublicNetIPv4 converts ServerPublicNetIPv4 to schema.ServerPublicNetIPv4.
func SchemaFromServerPublicNetIPv4(s1 ServerPublicNetIPv4) (s2 schema.ServerPublicNetIPv4) {
	return c.SchemaFromServerPublicNetIPv4(s1)
}

// SchemaFromServerPublicNetIPv6 converts ServerPublicNetIPv6 to schema.ServerPublicNetIPv6.
func SchemaFromServerPublicNetIPv6(s1 ServerPublicNetIPv6) (s2 schema.ServerPublicNetIPv6) {
	return c.SchemaFromServerPublicNetIPv6(s1)
}

// SchemaFromServerType converts *ServerType to schema.ServerType.
func SchemaFromServerType(sp1 *ServerType) (s1 schema.ServerType) {
	return c.SchemaFromServerType(sp1)
}

// SchemaFromStorageBox converts *StorageBox to schema.StorageBox.
func SchemaFromStorageBox(sp1 *StorageBox) (s1 schema.StorageBox) {
	return c.SchemaFromStorageBox(sp1)
}

// SchemaFromStorageBoxChangeProtectionOpts converts StorageBoxChangeProtectionOpts to schema.StorageBoxChangeProtectionRequest.
func SchemaFromStorageBoxChangeProtectionOpts(s1 StorageBoxChangeProtectionOpts) (s2 schema.StorageBoxChangeProtectionRequest) {
	return c.SchemaFromStorageBoxChangeProtectionOpts(s1)
}

// SchemaFromStorageBoxChangeTypeOpts converts StorageBoxChangeTypeOpts to schema.StorageBoxChangeTypeRequest.
func SchemaFromStorageBoxChangeTypeOpts(s1 StorageBoxChangeTypeOpts) (s2 schema.StorageBoxChangeTypeRequest) {
	return c.SchemaFromStorageBoxChangeTypeOpts(s1)
}

// SchemaFromStorageBoxCreateOpts converts StorageBoxCreateOpts to schema.StorageBoxCreateRequest.
func SchemaFromStorageBoxCreateOpts(s1 StorageBoxCreateOpts) (s2 schema.StorageBoxCreateRequest) {
	return c.SchemaFromStorageBoxCreateOpts(s1)
}

// SchemaFromStorageBoxEnableSnapshotPlanOpts converts StorageBoxEnableSnapshotPlanOpts to schema.StorageBoxEnableSnapshotPlanRequest.
func SchemaFromStorageBoxEnableSnapshotPlanOpts(s1 StorageBoxEnableSnapshotPlanOpts) (s2 schema.StorageBoxEnableSnapshotPlanRequest) {
	return c.SchemaFromStorageBoxEnableSnapshotPlanOpts(s1)
}

// SchemaFromStorageBoxResetPasswordOpts converts StorageBoxResetPasswordOpts to schema.StorageBoxResetPasswordRequest.
func SchemaFromStorageBoxResetPasswordOpts(s1 StorageBoxResetPasswordOpts) (s2 schema.StorageBoxResetPasswordRequest) {
	return c.SchemaFromStorageBoxResetPasswordOpts(s1)
}

// SchemaFromStorageBoxRollbackSnapshotOpts converts StorageBoxRollbackSnapshotOpts to schema.StorageBoxRollbackSnapshotRequest.
func SchemaFromStorageBoxRollbackSnapshotOpts(s1 StorageBoxRollbackSnapshotOpts) (s2 schema.StorageBoxRollbackSnapshotRequest) {
	return c.SchemaFromStorageBoxRollbackSnapshotOpts(s1)
}

// SchemaFromStorageBoxSnapshot converts *StorageBoxSnapshot to schema.StorageBoxSnapshot.
func SchemaFromStorageBoxSnapshot(sp1 *StorageBoxSnapshot) (s1 schema.StorageBoxSnapshot) {
	return c.SchemaFromStorageBoxSnapshot(sp1)
}

// SchemaFromStorageBoxSnapshotCreateOpts converts StorageBoxSnapshotCreateOpts to schema.StorageBoxSnapshotCreateRequest.
func SchemaFromStorageBoxSnapshotCreateOpts(s1 StorageBoxSnapshotCreateOpts) (s2 schema.StorageBoxSnapshotCreateRequest) {
	return c.SchemaFromStorageBoxSnapshotCreateOpts(s1)
}

// SchemaFromStorageBoxSnapshotUpdateOpts converts StorageBoxSnapshotUpdateOpts to schema.StorageBoxSnapshotUpdateRequest.
func SchemaFromStorageBoxSnapshotUpdateOpts(s1 StorageBoxSnapshotUpdateOpts) (s2 schema.StorageBoxSnapshotUpdateRequest) {
	return c.SchemaFromStorageBoxSnapshotUpdateOpts(s1)
}

// SchemaFromStorageBoxSubaccount converts *StorageBoxSubaccount to schema.StorageBoxSubaccount.
func SchemaFromStorageBoxSubaccount(sp1 *StorageBoxSubaccount) (s1 schema.StorageBoxSubaccount) {
	return c.SchemaFromStorageBoxSubaccount(sp1)
}

// SchemaFromStorageBoxSubaccountChangeHomeDirectoryOpts converts StorageBoxSubaccountChangeHomeDirectoryOpts to schema.StorageBoxSubaccountChangeHomeDirectoryRequest.
func SchemaFromStorageBoxSubaccountChangeHomeDirectoryOpts(s1 StorageBoxSubaccountChangeHomeDirectoryOpts) (s2 schema.StorageBoxSubaccountChangeHomeDirectoryRequest) {
	return c.SchemaFromStorageBoxSubaccountChangeHomeDirectoryOpts(s1)
}

// SchemaFromStorageBoxSubaccountCreateOpts converts StorageBoxSubaccountCreateOpts to schema.StorageBoxSubaccountCreateRequest.
func SchemaFromStorageBoxSubaccountCreateOpts(s1 StorageBoxSubaccountCreateOpts) (s2 schema.StorageBoxSubaccountCreateRequest) {
	return c.SchemaFromStorageBoxSubaccountCreateOpts(s1)
}

// SchemaFromStorageBoxSubaccountResetPasswordOpts converts StorageBoxSubaccountResetPasswordOpts to schema.StorageBoxSubaccountResetPasswordRequest.
func SchemaFromStorageBoxSubaccountResetPasswordOpts(s1 StorageBoxSubaccountResetPasswordOpts) (s2 schema.StorageBoxSubaccountResetPasswordRequest) {
	return c.SchemaFromStorageBoxSubaccountResetPasswordOpts(s1)
}

// SchemaFromStorageBoxSubaccountUpdateAccessSettingsOpts converts StorageBoxSubaccountUpdateAccessSettingsOpts to schema.StorageBoxSubaccountUpdateAccessSettingsRequest.
func SchemaFromStorageBoxSubaccountUpdateAccessSettingsOpts(s1 StorageBoxSubaccountUpdateAccessSettingsOpts) (s2 schema.StorageBoxSubaccountUpdateAccessSettingsRequest) {
	return c.SchemaFromStorageBoxSubaccountUpdateAccessSettingsOpts(s1)
}

// SchemaFromStorageBoxSubaccountUpdateOpts converts StorageBoxSubaccountUpdateOpts to schema.StorageBoxSubaccountUpdateRequest.
func SchemaFromStorageBoxSubaccountUpdateOpts(s1 StorageBoxSubaccountUpdateOpts) (s2 schema.StorageBoxSubaccountUpdateRequest) {
	return c.SchemaFromStorageBoxSubaccountUpdateOpts(s1)
}

// SchemaFromStorageBoxType converts *StorageBoxType to schema.StorageBoxType.
func SchemaFromStorageBoxType(sp1 *StorageBoxType) (s1 schema.StorageBoxType) {
	return c.SchemaFromStorageBoxType(sp1)
}

// SchemaFromStorageBoxUpdateAccessSettingsOpts converts StorageBoxUpdateAccessSettingsOpts to schema.StorageBoxUpdateAccessSettingsRequest.
func SchemaFromStorageBoxUpdateAccessSettingsOpts(s1 StorageBoxUpdateAccessSettingsOpts) (s2 schema.StorageBoxUpdateAccessSettingsRequest) {
	return c.SchemaFromStorageBoxUpdateAccessSettingsOpts(s1)
}

// SchemaFromStorageBoxUpdateOpts converts StorageBoxUpdateOpts to schema.StorageBoxUpdateRequest.
func SchemaFromStorageBoxUpdateOpts(s1 StorageBoxUpdateOpts) (s2 schema.StorageBoxUpdateRequest) {
	return c.SchemaFromStorageBoxUpdateOpts(s1)
}

// SchemaFromVolume converts *Volume to schema.Volume.
func SchemaFromVolume(vp1 *Volume) (v1 schema.Volume) {
	return c.SchemaFromVolume(vp1)
}

// SchemaFromZone converts *Zone to schema.Zone.
func SchemaFromZone(zp1 *Zone) (z1 schema.Zone) {
	return c.SchemaFromZone(zp1)
}

// SchemaFromZoneChangePrimaryNameserversOpts converts ZoneChangePrimaryNameserversOpts to schema.ZoneChangePrimaryNameserversRequest.
func SchemaFromZoneChangePrimaryNameserversOpts(z1 ZoneChangePrimaryNameserversOpts) (z2 schema.ZoneChangePrimaryNameserversRequest) {
	return c.SchemaFromZoneChangePrimaryNameserversOpts(z1)
}

// SchemaFromZoneChangeProtectionOpts converts ZoneChangeProtectionOpts to schema.ZoneChangeProtectionRequest.
func SchemaFromZoneChangeProtectionOpts(z1 ZoneChangeProtectionOpts) (z2 schema.ZoneChangeProtectionRequest) {
	return c.SchemaFromZoneChangeProtectionOpts(z1)
}

// SchemaFromZoneChangeTTLOpts converts ZoneChangeTTLOpts to schema.ZoneChangeTTLRequest.
func SchemaFromZoneChangeTTLOpts(z1 ZoneChangeTTLOpts) (z2 schema.ZoneChangeTTLRequest) {
	return c.SchemaFromZoneChangeTTLOpts(z1)
}

// SchemaFromZoneCreateOpts converts ZoneCreateOpts to schema.ZoneCreateRequest.
func SchemaFromZoneCreateOpts(z1 ZoneCreateOpts) (z2 schema.ZoneCreateRequest) {
	return c.SchemaFromZoneCreateOpts(z1)
}

// SchemaFromZoneImportZonefileOpts converts ZoneImportZonefileOpts to schema.ZoneImportZonefileRequest.
func SchemaFromZoneImportZonefileOpts(z1 ZoneImportZonefileOpts) (z2 schema.ZoneImportZonefileRequest) {
	return c.SchemaFromZoneImportZonefileOpts(z1)
}

// SchemaFromZoneRRSet converts *ZoneRRSet to schema.ZoneRRSet.
func SchemaFromZoneRRSet(zp1 *ZoneRRSet) (z1 schema.ZoneRRSet) {
	return c.SchemaFromZoneRRSet(zp1)
}

// SchemaFromZoneRRSetAddRecordsOpts converts ZoneRRSetAddRecordsOpts to schema.ZoneRRSetAddRecordsRequest.
func SchemaFromZoneRRSetAddRecordsOpts(z1 ZoneRRSetAddRecordsOpts) (z2 schema.ZoneRRSetAddRecordsRequest) {
	return c.SchemaFromZoneRRSetAddRecordsOpts(z1)
}

// SchemaFromZoneRRSetChangeProtectionOpts converts ZoneRRSetChangeProtectionOpts to schema.ZoneRRSetChangeProtectionRequest.
func SchemaFromZoneRRSetChangeProtectionOpts(z1 ZoneRRSetChangeProtectionOpts) (z2 schema.ZoneRRSetChangeProtectionRequest) {
	return c.SchemaFromZoneRRSetChangeProtectionOpts(z1)
}

// SchemaFromZoneRRSetChangeTTLOpts converts ZoneRRSetChangeTTLOpts to schema.ZoneRRSetChangeTTLRequest.
func SchemaFromZoneRRSetChangeTTLOpts(z1 ZoneRRSetChangeTTLOpts) (z2 schema.ZoneRRSetChangeTTLRequest) {
	return c.SchemaFromZoneRRSetChangeTTLOpts(z1)
}

// SchemaFromZoneRRSetCreateOpts converts ZoneRRSetCreateOpts to schema.ZoneRRSetCreateRequest.
func SchemaFromZoneRRSetCreateOpts(z1 ZoneRRSetCreateOpts) (z2 schema.ZoneRRSetCreateRequest) {
	return c.SchemaFromZoneRRSetCreateOpts(z1)
}

// SchemaFromZoneRRSetRemoveRecordsOpts converts ZoneRRSetRemoveRecordsOpts to schema.ZoneRRSetRemoveRecordsRequest.
func SchemaFromZoneRRSetRemoveRecordsOpts(z1 ZoneRRSetRemoveRecordsOpts) (z2 schema.ZoneRRSetRemoveRecordsRequest) {
	return c.SchemaFromZoneRRSetRemoveRecordsOpts(z1)
}

// SchemaFromZoneRRSetSetRecordsOpts converts ZoneRRSetSetRecordsOpts to schema.ZoneRRSetSetRecordsRequest.
func SchemaFromZoneRRSetSetRecordsOpts(z1 ZoneRRSetSetRecordsOpts) (z2 schema.ZoneRRSetSetRecordsRequest) {
	return c.SchemaFromZoneRRSetSetRecordsOpts(z1)
}

// SchemaFromZoneRRSetUpdateOpts converts ZoneRRSetUpdateOpts to schema.ZoneRRSetUpdateRequest.
func SchemaFromZoneRRSetUpdateOpts(z1 ZoneRRSetUpdateOpts) (z2 schema.ZoneRRSetUpdateRequest) {
	return c.SchemaFromZoneRRSetUpdateOpts(z1)
}

// SchemaFromZoneRRSetUpdateRecordsOpts converts ZoneRRSetUpdateRecordsOpts to schema.ZoneRRSetUpdateRecordsRequest.
func SchemaFromZoneRRSetUpdateRecordsOpts(z1 ZoneRRSetUpdateRecordsOpts) (z2 schema.ZoneRRSetUpdateRecordsRequest) {
	return c.SchemaFromZoneRRSetUpdateRecordsOpts(z1)
}

// SchemaFromZoneUpdateOpts converts ZoneUpdateOpts to schema.ZoneUpdateRequest.
func SchemaFromZoneUpdateOpts(z1 ZoneUpdateOpts) (z2 schema.ZoneUpdateRequest) {
	return c.SchemaFromZoneUpdateOpts(z1)
}

// ServerFromSchema converts schema.Server to *Server.
func ServerFromSchema(s1 schema.Server) (sp1 *Server) {
	return c.ServerFromSchema(s1)
}

// ServerMetricsFromSchema converts *schema.ServerGetMetricsResponse to *ServerMetrics.
func ServerMetricsFromSchema(sp1 *schema.ServerGetMetricsResponse) (sp2 *ServerMetrics, err error) {
	return c.ServerMetricsFromSchema(sp1)
}

// ServerPrivateNetFromSchema converts schema.ServerPrivateNet to ServerPrivateNet.
func ServerPrivateNetFromSchema(s1 schema.ServerPrivateNet) (s2 ServerPrivateNet) {
	return c.ServerPrivateNetFromSchema(s1)
}

// ServerPublicNetFromSchema converts schema.ServerPublicNet to ServerPublicNet.
func ServerPublicNetFromSchema(s1 schema.ServerPublicNet) (s2 ServerPublicNet) {
	return c.ServerPublicNetFromSchema(s1)
}

// ServerPublicNetIPv4FromSchema converts schema.ServerPublicNetIPv4 to ServerPublicNetIPv4.
func ServerPublicNetIPv4FromSchema(s1 schema.ServerPublicNetIPv4) (s2 ServerPublicNetIPv4) {
	return c.ServerPublicNetIPv4FromSchema(s1)
}

// ServerPublicNetIPv6FromSchema converts schema.ServerPublicNetIPv6 to ServerPublicNetIPv6.
func ServerPublicNetIPv6FromSchema(s1 schema.ServerPublicNetIPv6) (s2 ServerPublicNetIPv6) {
	return c.ServerPublicNetIPv6FromSchema(s1)
}

// ServerTypeFromSchema converts schema.ServerType to *ServerType.
func ServerTypeFromSchema(s1 schema.ServerType) (sp1 *ServerType) {
	return c.ServerTypeFromSchema(s1)
}

// StorageBoxFromSchema converts schema.StorageBox to *StorageBox.
func StorageBoxFromSchema(s1 schema.StorageBox) (sp1 *StorageBox) {
	return c.StorageBoxFromSchema(s1)
}

// StorageBoxSnapshotFromSchema converts schema.StorageBoxSnapshot to *StorageBoxSnapshot.
func StorageBoxSnapshotFromSchema(s1 schema.StorageBoxSnapshot) (sp1 *StorageBoxSnapshot) {
	return c.StorageBoxSnapshotFromSchema(s1)
}

// StorageBoxSnapshotPlanFromSchema converts schema.StorageBoxSnapshotPlan to StorageBoxSnapshotPlan.
func StorageBoxSnapshotPlanFromSchema(s1 schema.StorageBoxSnapshotPlan) (s2 StorageBoxSnapshotPlan) {
	return c.StorageBoxSnapshotPlanFromSchema(s1)
}

// StorageBoxSubaccountFromCreateResponse converts schema.StorageBoxSubaccountCreateResponseSubaccount to *StorageBoxSubaccount.
func StorageBoxSubaccountFromCreateResponse(s1 schema.StorageBoxSubaccountCreateResponseSubaccount) (sp1 *StorageBoxSubaccount) {
	return c.StorageBoxSubaccountFromCreateResponse(s1)
}

// StorageBoxSubaccountFromSchema converts schema.StorageBoxSubaccount to *StorageBoxSubaccount.
func StorageBoxSubaccountFromSchema(s1 schema.StorageBoxSubaccount) (sp1 *StorageBoxSubaccount) {
	return c.StorageBoxSubaccountFromSchema(s1)
}

// StorageBoxTypeFromSchema converts schema.StorageBoxType to *StorageBoxType.
func StorageBoxTypeFromSchema(s1 schema.StorageBoxType) (sp1 *StorageBoxType) {
	return c.StorageBoxTypeFromSchema(s1)
}

// VolumeFromSchema converts schema.Volume to *Volume.
func VolumeFromSchema(v1 schema.Volume) (vp1 *Volume) {
	return c.VolumeFromSchema(v1)
}

// ZoneFromSchema converts schema.Zone to *Zone.
func ZoneFromSchema(z1 schema.Zone) (zp1 *Zone) {
	return c.ZoneFromSchema(z1)
}

// ZoneRRSetFromSchema converts schema.ZoneRRSet to *ZoneRRSet.
func ZoneRRSetFromSchema(z1 schema.ZoneRRSet) (zp1 *ZoneRRSet) {
	return c.ZoneRRSetFromSchema(z1)
}

// ZoneRRSetRecordFromSchema converts schema.ZoneRRSetRecord to *ZoneRRSetRecord.
func ZoneRRSetRecordFromSchema(z1 schema.ZoneRRSetRecord) (zp1 *ZoneRRSetRecord) {
	return c.ZoneRRSetRecordFromSchema(z1)
}

// intISOFromSchema converts schema.ISO to ISO.
func intISOFromSchema(i1 schema.ISO) (i2 ISO) {
	return c.intISOFromSchema(i1)
}

// intSchemaFromImage converts Image to schema.Image.
func intSchemaFromImage(i1 Image) (i2 schema.Image) {
	return c.intSchemaFromImage(i1)
}

// schemaFromDatacenterServerTypes converts DatacenterServerTypes to schema.DatacenterServerTypes.
func schemaFromDatacenterServerTypes(d1 DatacenterServerTypes) (d2 schema.DatacenterServerTypes) {
	return c.schemaFromDatacenterServerTypes(d1)
}

// schemaFromFloatingIPPricing converts FloatingIPPricing to schema.PricingFloatingIP.
func schemaFromFloatingIPPricing(f1 FloatingIPPricing) (p1 schema.PricingFloatingIP) {
	return c.schemaFromFloatingIPPricing(f1)
}

// schemaFromFloatingIPTypeLocationPricing converts FloatingIPTypeLocationPricing to schema.PricingFloatingIPTypePrice.
func schemaFromFloatingIPTypeLocationPricing(f1 FloatingIPTypeLocationPricing) (p1 schema.PricingFloatingIPTypePrice) {
	return c.schemaFromFloatingIPTypeLocationPricing(f1)
}

// schemaFromFloatingIPTypePricing converts FloatingIPTypePricing to schema.PricingFloatingIPType.
func schemaFromFloatingIPTypePricing(f1 FloatingIPTypePricing) (p1 schema.PricingFloatingIPType) {
	return c.schemaFromFloatingIPTypePricing(f1)
}

// schemaFromImagePricing converts ImagePricing to schema.PricingImage.
func schemaFromImagePricing(i1 ImagePricing) (p1 schema.PricingImage) {
	return c.schemaFromImagePricing(i1)
}

// schemaFromLoadBalancerTypePricing converts LoadBalancerTypePricing to schema.PricingLoadBalancerType.
func schemaFromLoadBalancerTypePricing(l1 LoadBalancerTypePricing) (p1 schema.PricingLoadBalancerType) {
	return c.schemaFromLoadBalancerTypePricing(l1)
}

// schemaFromPrimaryIPPricing converts PrimaryIPPricing to schema.PricingPrimaryIP.
func schemaFromPrimaryIPPricing(p1 PrimaryIPPricing) (p2 schema.PricingPrimaryIP) {
	return c.schemaFromPrimaryIPPricing(p1)
}

// schemaFromPrimaryIPTypePricing converts PrimaryIPTypePricing to schema.PricingPrimaryIPTypePrice.
func schemaFromPrimaryIPTypePricing(p1 PrimaryIPTypePricing) (p2 schema.PricingPrimaryIPTypePrice) {
	return c.schemaFromPrimaryIPTypePricing(p1)
}

// schemaFromServerTypeLocation converts ServerTypeLocation to schema.ServerTypeLocation.
func schemaFromServerTypeLocation(location ServerTypeLocation) (s1 schema.ServerTypeLocation) {
	return c.schemaFromServerTypeLocation(location)
}

// schemaFromServerTypeLocationPricing converts ServerTypeLocationPricing to schema.PricingServerTypePrice.
func schemaFromServerTypeLocationPricing(s1 ServerTypeLocationPricing) (p1 schema.PricingServerTypePrice) {
	return c.schemaFromServerTypeLocationPricing(s1)
}

// schemaFromServerTypePricing converts ServerTypePricing to schema.PricingServerType.
func schemaFromServerTypePricing(s1 ServerTypePricing) (p1 schema.PricingServerType) {
	return c.schemaFromServerTypePricing(s1)
}

// schemaFromTrafficPricing converts TrafficPricing to schema.PricingTraffic.
func schemaFromTrafficPricing(t1 TrafficPricing) (p1 schema.PricingTraffic) {
	return c.schemaFromTrafficPricing(t1)
}

// schemaFromVolumePricing converts VolumePricing to schema.PricingVolume.
func schemaFromVolumePricing(v1 VolumePricing) (p1 schema.PricingVolume) {
	return c.schemaFromVolumePricing(v1)
}

// serverTypeLocationFromSchema converts schema.ServerTypeLocation to ServerTypeLocation.
func serverTypeLocationFromSchema(s1 schema.ServerTypeLocation) (s2 ServerTypeLocation) {
	return c.serverTypeLocationFromSchema(s1)
}

// serverTypeLocationPricingFromSchema converts schema.PricingServerTypePrice to ServerTypeLocationPricing.
func serverTypeLocationPricingFromSchema(p1 schema.PricingServerTypePrice) (s1 ServerTypeLocationPricing) {
	return c.serverTypeLocationPricingFromSchema(p1)
}
