// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hetznercloud/hcloud-go/v2/hcloud (interfaces: IFirewallClient)
//
// Generated by this command:
//
//	mockgen -package mock -destination zz_firewall_client_mock.go -mock_names IFirewallClient=FirewallClient github.com/hetznercloud/hcloud-go/v2/hcloud IFirewallClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	hcloud "github.com/hetznercloud/hcloud-go/v2/hcloud"
	gomock "go.uber.org/mock/gomock"
)

// FirewallClient is a mock of IFirewallClient interface.
type FirewallClient struct {
	ctrl     *gomock.Controller
	recorder *FirewallClientMockRecorder
}

// FirewallClientMockRecorder is the mock recorder for FirewallClient.
type FirewallClientMockRecorder struct {
	mock *FirewallClient
}

// NewFirewallClient creates a new mock instance.
func NewFirewallClient(ctrl *gomock.Controller) *FirewallClient {
	mock := &FirewallClient{ctrl: ctrl}
	mock.recorder = &FirewallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FirewallClient) EXPECT() *FirewallClientMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *FirewallClient) All(arg0 context.Context) ([]*hcloud.Firewall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].([]*hcloud.Firewall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *FirewallClientMockRecorder) All(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*FirewallClient)(nil).All), arg0)
}

// AllWithOpts mocks base method.
func (m *FirewallClient) AllWithOpts(arg0 context.Context, arg1 hcloud.FirewallListOpts) ([]*hcloud.Firewall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllWithOpts", arg0, arg1)
	ret0, _ := ret[0].([]*hcloud.Firewall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllWithOpts indicates an expected call of AllWithOpts.
func (mr *FirewallClientMockRecorder) AllWithOpts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllWithOpts", reflect.TypeOf((*FirewallClient)(nil).AllWithOpts), arg0, arg1)
}

// ApplyResources mocks base method.
func (m *FirewallClient) ApplyResources(arg0 context.Context, arg1 *hcloud.Firewall, arg2 []hcloud.FirewallResource) ([]*hcloud.Action, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyResources", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*hcloud.Action)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ApplyResources indicates an expected call of ApplyResources.
func (mr *FirewallClientMockRecorder) ApplyResources(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyResources", reflect.TypeOf((*FirewallClient)(nil).ApplyResources), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *FirewallClient) Create(arg0 context.Context, arg1 hcloud.FirewallCreateOpts) (hcloud.FirewallCreateResult, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(hcloud.FirewallCreateResult)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *FirewallClientMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*FirewallClient)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *FirewallClient) Delete(arg0 context.Context, arg1 *hcloud.Firewall) (*hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*hcloud.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *FirewallClientMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*FirewallClient)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *FirewallClient) Get(arg0 context.Context, arg1 string) (*hcloud.Firewall, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*hcloud.Firewall)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *FirewallClientMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*FirewallClient)(nil).Get), arg0, arg1)
}

// GetByID mocks base method.
func (m *FirewallClient) GetByID(arg0 context.Context, arg1 int64) (*hcloud.Firewall, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*hcloud.Firewall)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *FirewallClientMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*FirewallClient)(nil).GetByID), arg0, arg1)
}

// GetByName mocks base method.
func (m *FirewallClient) GetByName(arg0 context.Context, arg1 string) (*hcloud.Firewall, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1)
	ret0, _ := ret[0].(*hcloud.Firewall)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByName indicates an expected call of GetByName.
func (mr *FirewallClientMockRecorder) GetByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*FirewallClient)(nil).GetByName), arg0, arg1)
}

// List mocks base method.
func (m *FirewallClient) List(arg0 context.Context, arg1 hcloud.FirewallListOpts) ([]*hcloud.Firewall, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*hcloud.Firewall)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *FirewallClientMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*FirewallClient)(nil).List), arg0, arg1)
}

// RemoveResources mocks base method.
func (m *FirewallClient) RemoveResources(arg0 context.Context, arg1 *hcloud.Firewall, arg2 []hcloud.FirewallResource) ([]*hcloud.Action, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResources", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*hcloud.Action)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RemoveResources indicates an expected call of RemoveResources.
func (mr *FirewallClientMockRecorder) RemoveResources(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResources", reflect.TypeOf((*FirewallClient)(nil).RemoveResources), arg0, arg1, arg2)
}

// SetRules mocks base method.
func (m *FirewallClient) SetRules(arg0 context.Context, arg1 *hcloud.Firewall, arg2 hcloud.FirewallSetRulesOpts) ([]*hcloud.Action, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRules", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*hcloud.Action)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetRules indicates an expected call of SetRules.
func (mr *FirewallClientMockRecorder) SetRules(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRules", reflect.TypeOf((*FirewallClient)(nil).SetRules), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *FirewallClient) Update(arg0 context.Context, arg1 *hcloud.Firewall, arg2 hcloud.FirewallUpdateOpts) (*hcloud.Firewall, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*hcloud.Firewall)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *FirewallClientMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*FirewallClient)(nil).Update), arg0, arg1, arg2)
}
