version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unparam
    - zerologlint

  settings:
    exhaustive:
      default-signifies-exhaustive: true
    staticcheck:
      checks: ["all", "-QF1008"]

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - noctx
        path: _test\.go
      - linters:
          - testifylint
        text: require-error
      - linters:
          - revive
        path: _test\.go
        text: "unused-parameter: parameter '(w|r)' seems to be unused, consider removing or renaming it as _"

formatters:
  enable:
    - gci
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hetznercloud)

  exclusions:
    generated: lax
