---
linters:
  presets:
    - bugs
    - error
    - import
    - metalinter
    - module
    - unused

  enable:
    - forbidigo
    - testifylint

  disable:
    # preset error
    - err113 # Very annoying to define static errors everywhere
    - wrapcheck # Very annoying to wrap errors everywhere
    # preset import
    - depguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hetznercloud)

  exhaustive:
    # Switch cases with a default case should be exhaustive.
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx

    - path: _test\.go
      linters:
        - revive
      text: "unused-parameter: parameter '(w|r)' seems to be unused, consider removing or renaming it as _"

    - linters:
        - testifylint
      text: "require-error"
