name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - uses: jooola/backport@main
        # Using a fork of tibdex/backport@v2 to get https://github.com/tibdex/backport/pull/109
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # These templates are compatible with release-please and our default commit body (body of PR).
          title_template: "<%= title %> [Backport <%= base %>]"
          body_template: |
            <%= body %>
            
            ---
            Backport <%= mergeCommitSha %> from #<%= number %>.
            
            BEGIN_COMMIT_OVERRIDE
            <%= title %>
            END_COMMIT_OVERRIDE
